### ISSUE TITLE
Add error handling to compile script if something goes wrong with gulp build

### ISSUE THREAD

**Issue by elysiandc** [philcon93/ntheme#13]
Was having a play around with this to see what would happen if I compiled a theme with [Bootstrap Material Design (BMD)](https://fezvrasta.github.io/bootstrap-material-design/) replacing Bootstrap. There were some references to Bootstrap SCSS in the BMD SCSS which caused the build to fail. Once I corrected these the build was successful.

I was only able to identify the source of the error with `npm run build`, but `ntheme compile -u` doesn't show these and comes back saying the build is successful.

Not a major issue, but could be good to have.

**Comment by philcon93** [comment]
Hey @elysiandc, if `npm run build` is failing, then that would be an issue with what is happening when you run the gulp build task. I have a sneaky suspicion it might be because the Skeletal SASS partial `_neto ` has bootstrap variables in it, and if you have changes `app.scss` to no longer look for bootstrap but material bootstrap, it might not have the same variables.

- https://github.com/NetoECommerce/Country-Theme/blob/master/src/scss/app.scss 
- https://github.com/NetoECommerce/Skeletal/blob/master/src/scss/_neto.scss#L41

What is your repo, I might be able to help out? We might just need to update your theme to have a `_neto` and it to have the variables declared at the top of the partial.

**Comment by elysiandc** [comment]
Hey @philcon93, this being my first cut at building a custom theme I'm not super versed at all the ins-and-outs, so you may be on to something. I kind of hacked my way through until it worked.
To be clear, these are the specific things I found and changed, but I may have missed something...

- I [installed BMD](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/download/#package-managers) into node_modules/
- In package.json I changed line 33 to `"bootstrap-material-design": "^4.1.1"`
- In gulpfile.js I changed line 27 to 
`return src(['node_modules/jquery/dist/jquery.min.js', 'node_modules/popper.js/dist/umd/popper.min.js', 'node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.min.js'])`
- In various _xxxx.scss files in BMD (eg node_modules\bootstrap-material-design\scss\_variables.scss) there were references to ~/bootstrap/scss/xxxx.scs. By fixing the paths in these everything worked as it should.
- The last thing was to change to link to the CDN version of vendor.js to my local version in dist\evok3d\templates\footers\includes\scripts.template.html and that was it - a wonderfully butchered version of Skeletal. 

Would be good as a starting point if you wanted the familiar UI elements of Google Material with the layout foundation of Bootstrap. We had design services from Spotzer involved and they were too far down the track to make this work for us unfortunately.

All in all I wouldn't invest too much time in this. I found the issue and worked around it, just thought it would be nice to have some visibility of any errors thrown by `npm run build` popping through `ntheme compile -u`. I'd look into it further myself, but don't have the time unfortunately. While the Material Design for Bootstrap build was successful, it couldn't  be bent to our will in the time available so has been abandoned for the moment.

I didn't create a repo for the project as it was just a bit of a proof of concept, but happy to do so if you think it would be valuable for you.

Side note: This whole theme builder is pretty amazing. I've been burned by other eCommerce offerings around site customisation, so I think this is pretty dope. A great point of difference and well worth maintaining.

**Comment by philcon93** [comment]
I've been entertaining the idea to have a completely barebone version of Skeletal, so that developers could place in whatever CSS framework that works for them. Then with this `ntheme` tool, developers could generate a 'barebone' skeletal, a 'bootstrap' skeletal or even a 'material' skeletal. 

Definitely push up your theme into a git repo, I would love to see how you got it all going! I'm always switching computers and testing ideas, so with a git repo I can always access it on different devices and I can test ideas on branches that dont mess up the master branch.

I think what might have gone down is when you replaced `bootstrap` with `bootstrap-material-design` in the package.json, it didn't have this in your node modules anymore:

- https://github.com/FezVrasta/bootstrap-material-design/blob/master/scss/_core.scss#L4

Bootstrap is a devDependency to `bootstrap-material-design` so it wouldn't have this module in your project. This would be why you had to update the paths inside `\bootstrap-material-design\scss_variables.scss`. If you have both modules (`bootstrap` and `bootstrap-material-design`), you might not need to update these paths anymore and it should work.

I'll look into making the build script to have more useful messages.

**Comment by elysiandc** [comment]
I think you're onto something there with including both dependencies instead of kludging like I did. I might get around to testing it one day.

I'm not too well versed with Git, so hopefully I did this correctly...

https://github.com/elysiandc/Neto-EVOK3D-BMD-Theme
